# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import configparser,os
directory_path= os.path.dirname(__file__)
print(directory_path)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lhost_abel = QtWidgets.QLabel(self.centralwidget)
        self.lhost_abel.setGeometry(QtCore.QRect(60, 70, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lhost_abel.setFont(font)
        self.lhost_abel.setObjectName("lhost_abel")
        self.user_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.user_lineEdit.setGeometry(QtCore.QRect(210, 80, 231, 25))
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.submit_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.checked())
        self.submit_pushButton.setGeometry(QtCore.QRect(40, 210, 89, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.submit_pushButton.setFont(font)
        self.submit_pushButton.setObjectName("submit_pushButton")
        self.run_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.run_pushButton.setGeometry(QtCore.QRect(200, 210, 89, 25))
        self.run_pushButton.setObjectName("run_pushButton")
        self.op_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.op_pushButton.setGeometry(QtCore.QRect(370, 210, 89, 25))
        self.op_pushButton.setObjectName("op_pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 290, 791, 301))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lhost_abel.setText(_translate("MainWindow", "Hostname"))
        self.submit_pushButton.setText(_translate("MainWindow", "Submit"))
        self.run_pushButton.setText(_translate("MainWindow", "Run"))
        self.op_pushButton.setText(_translate("MainWindow", "Save Output"))

    def message(self,s):
        self.plainTextEdit.appendPlainText(s)

    def checked(self):
        self.plainTextEdit.clear()  
        a= open(r"{}requirement.ini".format(directory_path),'w') 
        try:
            f1=configparser.ConfigParser()
            f1.add_section("Section1")
            f1.set("Section1","hostname",self.user_lineEdit.text())
            f1.write(a)
            a.close
            self.plainTextEdit.appendPlainText("hostname: {}".format(self.user_lineEdit.text()))
            self.plainTextEdit.appendPlainText("Data append successfully")

        except Exception as e:
            print(e)
            pass     



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())
